# Generated by Django 6.0 on 2025-12-12 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDeCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('distancia_planejada_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Distância Planejada (km)')),
                ('duracao_estimada_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração Estimada (min)')),
                ('objetivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Objetivo do Treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_corrida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Modelo de Corrida',
                'verbose_name_plural': 'Modelos de Corrida',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Realização')),
                ('tempo_total_seg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total (segundos)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('modelo_corrida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.modelodecorrida', verbose_name='Modelo Associado')),
            ],
            options={
                'verbose_name': 'Histórico de Corrida',
                'verbose_name_plural': 'Histórico de Corridas',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
