# Generated by Django 6.0 on 2025-12-12 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocorrida',
            name='tempo_total_seg',
        ),
        migrations.AddField(
            model_name='historicocorrida',
            name='tempo_total_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total (minutos)'),
            preserve_default=False,
        ),
    ]
